'use strict';

const fs=require('fs');
const path=require('path');
const os=require('os');
const {DatabaseSync}=require('node:sqlite');

function persistentBaseDir(){const local=String(process.env.LOCALAPPDATA||'').trim();return local?path.join(local,'BrowserOS'):path.join(os.homedir(),'.browseros')}
function nowIso(){return new Date().toISOString()}
function asInt(v,fallback=0){const n=Number(v);return Number.isFinite(n)?Math.trunc(n):fallback}
function safeJson(text,fallback={}){try{const v=JSON.parse(String(text||''));return v&&typeof v==='object'?v:fallback}catch{return fallback}}
function parseFieldToken(token,min,max,{dow=false}={}){const values=new Set(),normalized=String(token||'*').trim();const add=n=>{let v=Number(n);if(dow&&v===7)v=0;if(Number.isInteger(v)&&v>=min&&v<=max)values.add(v)};for(const raw of normalized.split(',')){const part=raw.trim();if(!part)continue;const [baseRaw,stepRaw]=part.split('/');const step=Math.max(1,asInt(stepRaw,1)),base=(baseRaw||'*').trim();let start=min,end=max;if(base!=='*'){if(base.includes('-')){const [a,b]=base.split('-',2).map(Number);start=a;end=b}else start=end=Number(base)}if(dow){if(start===7)start=0;if(end===7)end=0}if(!Number.isInteger(start)||!Number.isInteger(end))throw new Error('Invalid recurring schedule.');if(dow&&start>end&&base.includes('-')){for(let n=start;n<=6;n+=step)add(n);for(let n=0;n<=end;n+=step)add(n);continue}if(start<min||start>max||end<min||end>max||start>end)throw new Error('Invalid recurring schedule.');for(let n=start;n<=end;n+=step)add(n)}if(!values.size)throw new Error('Invalid recurring schedule.');return values}
function compileCron(expression){const raw=String(expression||'').trim(),f=raw.split(/\s+/);if(f.length!==5)throw new Error('Invalid recurring schedule.');const [minute,hour,dom,month,dow]=f;return{raw,minute:parseFieldToken(minute,0,59),hour:parseFieldToken(hour,0,23),dom:parseFieldToken(dom,1,31),month:parseFieldToken(month,1,12),dow:parseFieldToken(dow,0,6,{dow:true}),domAny:dom==='*',dowAny:dow==='*'}}
function cronMatches(c,d){if(!c.minute.has(d.getMinutes())||!c.hour.has(d.getHours())||!c.month.has(d.getMonth()+1))return false;const dm=c.dom.has(d.getDate()),dw=c.dow.has(d.getDay());return c.domAny&&c.dowAny?true:c.domAny?dw:c.dowAny?dm:(dm||dw)}
function nextCronTime(expression,afterMs=Date.now()){const c=compileCron(expression),d=new Date(afterMs);d.setSeconds(0,0);d.setMinutes(d.getMinutes()+1);for(let i=0;i<60*24*366*2;i++){if(cronMatches(c,d))return d.getTime();d.setMinutes(d.getMinutes()+1)}throw new Error('Could not calculate the next scheduled run.')}
function publicJob(row){if(!row)return null;const config=safeJson(row.config_json,{});return{id:row.id,slug:row.slug,name:row.name,enabled:!!row.enabled,cron:row.cron_expr,timezone:row.timezone||'local',job_type:row.job_type,handler:row.handler,prompt:row.prompt||'',config,miss_policy:row.miss_policy,max_lateness_minutes:row.max_lateness_minutes,next_run_ms:row.next_run_ms,last_run_ms:row.last_run_ms,running:!!row.running,lease_until_ms:row.lease_until_ms,created_at:row.created_at,updated_at:row.updated_at}}
function publicRun(row){return row?{id:row.id,job_id:row.job_id,scheduled_for_ms:row.scheduled_for_ms,started_at:row.started_at,finished_at:row.finished_at,status:row.status,result:row.result||'',error:row.error||'',unread:!!row.unread,context_chars:row.context_chars||0,meta:safeJson(row.meta_json,{})}:null}

class CronScheduler{
  constructor({executor,onEvent,maxSleepMs=60000}){this.executor=executor;this.onEvent=typeof onEvent==='function'?onEvent:()=>{};this.maxSleepMs=Math.max(1000,maxSleepMs);this.dbPath=path.join(persistentBaseDir(),'cron.db');fs.mkdirSync(path.dirname(this.dbPath),{recursive:true});this.db=new DatabaseSync(this.dbPath);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');this.timer=null;this.running=false;this.executionLane=Promise.resolve();this.initSchema();this.recoverStaleRuns();this.migrateLegacy()}
  initSchema(){this.db.exec(`CREATE TABLE IF NOT EXISTS cron_jobs (id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT UNIQUE,name TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,cron_expr TEXT NOT NULL,timezone TEXT NOT NULL DEFAULT 'local',job_type TEXT NOT NULL DEFAULT 'task',handler TEXT NOT NULL DEFAULT '',prompt TEXT NOT NULL DEFAULT '',config_json TEXT NOT NULL DEFAULT '{}',miss_policy TEXT NOT NULL DEFAULT 'run_if_recent',max_lateness_minutes INTEGER NOT NULL DEFAULT 240,next_run_ms INTEGER,last_run_ms INTEGER,running INTEGER NOT NULL DEFAULT 0,lease_until_ms INTEGER,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE IF NOT EXISTS cron_runs (id INTEGER PRIMARY KEY AUTOINCREMENT,job_id INTEGER NOT NULL,scheduled_for_ms INTEGER NOT NULL,started_at TEXT,finished_at TEXT,status TEXT NOT NULL,result TEXT NOT NULL DEFAULT '',error TEXT NOT NULL DEFAULT '',unread INTEGER NOT NULL DEFAULT 0,context_chars INTEGER NOT NULL DEFAULT 0,meta_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(job_id) REFERENCES cron_jobs(id) ON DELETE CASCADE);CREATE INDEX IF NOT EXISTS cron_jobs_due_idx ON cron_jobs(enabled,next_run_ms);CREATE INDEX IF NOT EXISTS cron_runs_job_idx ON cron_runs(job_id,id DESC);`)}
  recoverStaleRuns(){const now=Date.now();this.db.prepare('UPDATE cron_jobs SET running=0,lease_until_ms=NULL WHERE running=1 AND COALESCE(lease_until_ms,0) < ?').run(now);this.db.prepare("UPDATE cron_runs SET status='interrupted',finished_at=?,error=CASE WHEN error='' THEN 'BrowserOS stopped before this run completed.' ELSE error END WHERE status='running'").run(nowIso())}
  migrateLegacy(){const s=this.db.prepare('SELECT id FROM cron_jobs WHERE slug=?').get('stevens-morning-brief');if(s){this.db.prepare('DELETE FROM cron_runs WHERE job_id=?').run(s.id);this.db.prepare('DELETE FROM cron_jobs WHERE id=?').run(s.id)}/* Keep other user-created legacy jobs visible; the UI maps agent_prompt to AI-assisted tasks. */}
  start(){if(this.running)return;this.running=true;this.wake(50)}
  stop(){this.running=false;if(this.timer)clearTimeout(this.timer);this.timer=null}
  wake(delay=0){if(!this.running)return;if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>this.tick().catch(e=>console.error('[Scheduled Tasks]',e)),Math.max(0,delay))}
  listJobs(){return this.db.prepare('SELECT * FROM cron_jobs ORDER BY COALESCE(next_run_ms,9223372036854775807),id').all().map(publicJob)}
  getJob(id){return publicJob(this.db.prepare('SELECT * FROM cron_jobs WHERE id=?').get(asInt(id)))}
  listRuns({jobId=null,limit=30}={}){limit=Math.max(1,Math.min(100,asInt(limit,30)));const rows=jobId?this.db.prepare('SELECT * FROM cron_runs WHERE job_id=? ORDER BY id DESC LIMIT ?').all(asInt(jobId),limit):this.db.prepare('SELECT * FROM cron_runs ORDER BY id DESC LIMIT ?').all(limit);return rows.map(publicRun)}
  getRun(id){return publicRun(this.db.prepare('SELECT * FROM cron_runs WHERE id=?').get(asInt(id)))}
  updateRunMeta(id,patch={}){const row=this.db.prepare('SELECT meta_json FROM cron_runs WHERE id=?').get(asInt(id));if(!row)throw new Error('Task run not found.');const meta={...safeJson(row.meta_json,{}),...(patch&&typeof patch==='object'?patch:{})};this.db.prepare('UPDATE cron_runs SET meta_json=? WHERE id=?').run(JSON.stringify(meta),asInt(id));return this.getRun(id)}
  markRunRead(id){this.db.prepare('UPDATE cron_runs SET unread=0 WHERE id=?').run(asInt(id));return true}
  clearRuns(jobId){const id=asInt(jobId);const job=this.db.prepare('SELECT id FROM cron_jobs WHERE id=?').get(id);if(!job)throw new Error('Task not found.');const r=this.db.prepare('DELETE FROM cron_runs WHERE job_id=?').run(id);return Number(r.changes||0)}
  normalizeInput(input={},current=null){
    const name=input.name===undefined?String(current?.name||'').trim():String(input.name||'').trim();if(!name)throw new Error('Task name is required.');
    const oldCfg=current?safeJson(current.config_json,{}):{};const config=input.config===undefined?oldCfg:(input.config&&typeof input.config==='object'?input.config:{});
    const jobType=String(input.job_type===undefined?(current?.job_type||'task'):input.job_type||'task');if(!['task','agent_prompt','builtin'].includes(jobType))throw new Error('Unsupported task type.');
    const handler=String(input.handler===undefined?(current?.handler||''):input.handler||'');const prompt=String(input.prompt===undefined?(current?.prompt||''):input.prompt||'');
    const enabled=input.enabled===undefined?(current?!!current.enabled:true):!!input.enabled;
    const once=String(config.schedule_kind||'')==='once';const cron=String(input.cron===undefined&&input.cron_expr===undefined?(current?.cron_expr||'0 9 * * *'):(input.cron??input.cron_expr)||'0 9 * * *').trim();
    let nextRun;if(once){nextRun=Number(config.once_at_ms||0);if(!Number.isFinite(nextRun)||nextRun<=Date.now())throw new Error('Choose a future date and time.');}else{compileCron(cron);const cronChanged=!current||cron!==current.cron_expr||String(oldCfg.schedule_kind||'')==='once';nextRun=cronChanged||(!current?.enabled&&enabled)?nextCronTime(cron,Date.now()):current.next_run_ms;if(!enabled&&nextRun==null)nextRun=nextCronTime(cron,Date.now());}
    const missPolicy=['skip','run_once','run_if_recent'].includes(input.miss_policy)?input.miss_policy:(current?.miss_policy||'run_if_recent');const maxLate=input.max_lateness_minutes===undefined?(current?.max_lateness_minutes||240):Math.max(1,asInt(input.max_lateness_minutes,240));
    return{name,config,jobType,handler,prompt,enabled,once,cron,nextRun,missPolicy,maxLate};
  }
  createJob(input={}){const x=this.normalizeInput(input,null);const r=this.db.prepare('INSERT INTO cron_jobs (slug,name,enabled,cron_expr,timezone,job_type,handler,prompt,config_json,miss_policy,max_lateness_minutes,next_run_ms,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(input.slug?String(input.slug):null,x.name,x.enabled?1:0,x.cron,'local',x.jobType,x.handler,x.prompt,JSON.stringify(x.config),x.missPolicy,x.maxLate,x.nextRun,nowIso(),nowIso());this.wake();return this.getJob(r.lastInsertRowid)}
  updateJob(id,input={}){const row=this.db.prepare('SELECT * FROM cron_jobs WHERE id=?').get(asInt(id));if(!row)throw new Error('Task not found.');const x=this.normalizeInput(input,row);this.db.prepare('UPDATE cron_jobs SET name=?,enabled=?,cron_expr=?,job_type=?,handler=?,prompt=?,config_json=?,miss_policy=?,max_lateness_minutes=?,next_run_ms=?,updated_at=? WHERE id=?').run(x.name,x.enabled?1:0,x.cron,x.jobType,x.handler,x.prompt,JSON.stringify(x.config),x.missPolicy,x.maxLate,x.nextRun,nowIso(),asInt(id));this.wake();return this.getJob(id)}
  deleteJob(id){const row=this.db.prepare('SELECT id FROM cron_jobs WHERE id=?').get(asInt(id));if(!row)return false;this.db.prepare('DELETE FROM cron_runs WHERE job_id=?').run(asInt(id));this.db.prepare('DELETE FROM cron_jobs WHERE id=?').run(asInt(id));this.wake();return true}
  runNow(id){const row=this.db.prepare('SELECT * FROM cron_jobs WHERE id=?').get(asInt(id));if(!row)throw new Error('Task not found.');const at=Date.now();this.enqueueExecution(row,at,{manual:true});return{queued:true,job:publicJob(row),scheduled_for_ms:at}}
  async tick(){if(!this.running)return;const now=Date.now(),due=this.db.prepare('SELECT * FROM cron_jobs WHERE enabled=1 AND next_run_ms IS NOT NULL AND next_run_ms<=? ORDER BY next_run_ms,id').all(now);for(const row of due)this.handleDue(row,now);const next=this.db.prepare('SELECT MIN(next_run_ms) AS n FROM cron_jobs WHERE enabled=1 AND next_run_ms IS NOT NULL').get()?.n;this.wake(next==null?this.maxSleepMs:Math.max(250,Math.min(this.maxSleepMs,Number(next)-Date.now())))}
  handleDue(row,now){const scheduled=Number(row.next_run_ms||now),lateness=Math.max(0,now-scheduled),maxLate=Math.max(1,Number(row.max_lateness_minutes||240))*60000,skip=row.miss_policy==='skip'||(row.miss_policy==='run_if_recent'&&lateness>maxLate),cfg=safeJson(row.config_json,{}),isOnce=String(cfg.schedule_kind||'')==='once';const next=isOnce?null:nextCronTime(row.cron_expr,Math.max(now,scheduled));this.db.prepare('UPDATE cron_jobs SET enabled=?,next_run_ms=?,updated_at=? WHERE id=?').run(isOnce?0:row.enabled,next,nowIso(),row.id);if(skip){this.db.prepare('INSERT INTO cron_runs(job_id,scheduled_for_ms,started_at,finished_at,status,error,unread) VALUES(?,?,?,?,?,?,0)').run(row.id,scheduled,nowIso(),nowIso(),'skipped',`Missed by ${Math.round(lateness/60000)} minutes.`);this.onEvent({type:'task_skipped',job:this.getJob(row.id),run:this.listRuns({jobId:row.id,limit:1})[0]});return}this.enqueueExecution(row,scheduled,{manual:false})}
  enqueueExecution(row,scheduled,{manual=false}={}){const now=Date.now(),lease=now+15*60*1000,claim=this.db.prepare('UPDATE cron_jobs SET running=1,lease_until_ms=? WHERE id=? AND (running=0 OR COALESCE(lease_until_ms,0)<?)').run(lease,row.id,now);if(!claim.changes)return;const ri=this.db.prepare('INSERT INTO cron_runs(job_id,scheduled_for_ms,started_at,status,unread) VALUES(?,?,?,?,0)').run(row.id,scheduled,nowIso(),'running'),runId=Number(ri.lastInsertRowid);const execute=async()=>{try{const result=await this.executor(publicJob(row),{scheduledForMs:scheduled,manual}),text=String(result?.text||result?.result||'').trim();this.db.prepare("UPDATE cron_runs SET finished_at=?,status='success',result=?,unread=1,context_chars=?,meta_json=? WHERE id=?").run(nowIso(),text,asInt(result?.context_chars,0),JSON.stringify(result?.meta||{}),runId);this.db.prepare('UPDATE cron_jobs SET running=0,lease_until_ms=NULL,last_run_ms=?,updated_at=? WHERE id=?').run(Date.now(),nowIso(),row.id);this.onEvent({type:'task_result',job:this.getJob(row.id),run:this.listRuns({jobId:row.id,limit:1})[0]})}catch(e){const msg=String(e?.message||e);this.db.prepare("UPDATE cron_runs SET finished_at=?,status='error',error=?,unread=1 WHERE id=?").run(nowIso(),msg,runId);this.db.prepare('UPDATE cron_jobs SET running=0,lease_until_ms=NULL,last_run_ms=?,updated_at=? WHERE id=?').run(Date.now(),nowIso(),row.id);this.onEvent({type:'task_error',job:this.getJob(row.id),run:this.listRuns({jobId:row.id,limit:1})[0]})}};this.executionLane=this.executionLane.then(execute,execute)}
}
module.exports={CronScheduler,compileCron,nextCronTime,persistentBaseDir};
